# -*- coding: utf-8 -*-
"""Atividade 1 - Mário Narcizo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yOpUE3agmCpIujYDfc5ASQls0DEoIOph
"""

from time import sleep

#Boas Vindas
print("Olá, seja bem-vindo(a) a SENAI Tour\n")

#Inicialização da Variável de Controle do laço
opcao = 0

#Criação da Classe Destino
class Destino:
  #Inicializador de destinos
  def __init__(self, nome, clima, lugar, verba):
    self.nome = nome
    self.clima = clima
    self.lugar = lugar
    self.verba = verba

  def __str__(self):
    return f"{self.nome} | {self.clima} | {self.lugar} | {self.verba}"

  #Método para verificar o melhor destino
  def destino_ideal(self, clima, lugar, verba):
    return(self.clima == clima and self.lugar == lugar and self.verba >= verba)


  #Método para Cadastro de novos destinos
  def cadastrar_destino():
    print("\nOlá, vamos cadastrar um novo destino.")

    nome = input("\nQual o nome do destino? ")
    clima = input(f"{nome} tem Clima Quente ou Frio? Responda com [Quente] ou [Frio] ")
    lugar = input(f"{nome} é um lugar com natureza ou paisagem urbana? Responda com [Natureza] ou [Urbana] ")
    verba = float(input(f"Qual o orçamento disponível para a viajar para {nome}? "))

    destinos.append(Destino(nome, clima, lugar, verba))
    print(f"\nDestino {nome} cadastrado com sucesso! Segue a nova lista de destinos:")

    for i in destinos:
      print(i)

    print()

  #Método para Remoção de destinos
  def remover_destino():
    print("\nOlá, vamos remover um destino.")

    nome = input("\nQual o nome do destino? ")

    for destino in destinos:
      if destino.nome == nome:
        destinos.remove(destino)
        print("\nDestino removido com sucesso! Segue a nova lista de Destinos: ")

    for i in destinos:
      print(i)

    print()


#Criação da lista com vários destinos
destinos = [
  Destino("Rio de Janeiro", "Quente", "Urbana", 2000),
  Destino("Gramado", "Frio", "Urbana", 2500),
  Destino("Lençóis Maranhenses", "Quente", "Natureza", 1800),
  Destino("Rio de Janeiro", "Quente", "Urbana", 2000),
  Destino("Gramado", "Frio", "Urbana", 2500),
  Destino("Lençóis Maranhenses", "Quente", "Natureza", 1800)
]

#Inicialização do Laço
while opcao != 5:

  #Menu de Opções:
  print("""[1] Cadastrar Destino
[2] Remover Destino
[3] Verificar Destino Ideal
[4] Verificar Lista de Destinos
[5] Sair\n""")

  opcao = int(input("Escolha uma opção: "))

  if opcao == 1:
    Destino.cadastrar_destino()
  elif opcao == 2:
    Destino.remover_destino()
  elif opcao == 3:
    clima = input(f"Qual o Clima ideal para sua viagem? Responda com [Quente] ou [Frio] ")
    lugar = input(f"Qual ambiente é o ideal para sua viagem? Responda com [Natureza] ou [Urbana] ")
    verba = float(input(f"Qual o orçamento disponível para a viajar? "))

    print("\nVerificando........")
    sleep(2)
    print(f"\nSegue alguma(s) sugestão(ões) de destino(s):")

    for destino in destinos:
      if destino.destino_ideal(clima, lugar, verba):
        print(f"{destino.nome}")

    print()

  elif opcao == 4:
    print("\nSegue a lista de destinos:")
    for i in destinos:
      print(i)

    print()

  else:
    print("\nOpção Inválida, tente novamente.")

print("Obrigado por utilizar nossos serviços, volte sempre!")

