# -*- coding: utf-8 -*-
"""Atividade 03 - Mário Narcizo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11XhxYjx0-4zXn3uMnNAEoPlFR4YYskd1

**Cenário Hipotético: Monitoramento de uma Caldeira**
"""

!pip install emoji

#Importando biblioteca(s)
import numpy as np
import emoji


#Variáveis Auxiliares
i = 0

#Conjunto de Dados das Temperaturas
medicoes = []

#Criação da Classe
class monitoramento_temperatura:

  def add_leitura():
    print("\nVamos adicionar uma nova medição de temperatura da Caldeira")
    temp = float(input("\nDigite a temperatura medida: "))
    medicoes.append(temp)

    if temp >= 20 and temp <=80:
      print(emoji.emojize("\nLeitura Segura! :check_mark_button:"))
    elif temp < 20:
      print(emoji.emojize("\nALERTA DE SEGURANÇA: Leitura Muito Baixa! :stop_sign:"))
    else:
      print(emoji.emojize("\nALERTA DE SEGURANÇA: Leitura Muito Alta! :stop_sign:"))

  def verificar_leituras():
    if len(medicoes) == 0:
      print("\nNenhuma Leitura Cadastrada!")
    else:
      print("\nSegue a Lista de Todas as Leituras de Temperatura:\n")
      for temp in medicoes:
        print(f"{medicoes.index(temp)+1}º - {temp:.1f}ºC")


  def calculos_estatisticos():
    if len(medicoes) == 0:
      print("\nNenhuma Leitura Cadastrada!")

    else:
      print("\nVamos Realizar uma Análise Estatística:")
      print(f"""Média: {np.mean(medicoes)}ºC
Valor Mínimo: {np.min(medicoes)}ºC
Valor Máximo: {np.max(medicoes)}ºC
Desvio Padrão: {np.std(medicoes)}""")
      np.histogram(medicoes)


opcao = 0

while opcao != 4:
  print("""\nMONITORAMENTO DA CALDEIRA PRIMÁRIA]
[1] - Adicionar Leitura
[2] - Verificar Leituras Cadastradas
[3] - Realizar Cálculos Estatísticos
[4] - Sair""")

  opcao = int(input("\nDigite a opção desejada: "))

  if opcao == 1:
    monitoramento_temperatura.add_leitura()
  elif opcao == 2:
    monitoramento_temperatura.verificar_leituras()
  elif opcao == 3:
    monitoramento_temperatura.calculos_estatisticos()
  elif opcao < 1 or opcao > 4:
    print("\nOpção Inválida! Tente Novamente!")


print("\nVolte Sempre!")

